/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dtP1NMgzjkk
 */
import ReactPlayer from "react-player";

export function YoutubeGrid({ urls }: { urls: string[] }) {
  return (
    <div className="grid grid-cols-4 gap-4">
      {urls.map((url, index) => (
        <div className="relative group" key={index}>
          <ReactPlayer
            url={url}
            controls
            playing
            loop
            muted
            width="356"
            height="200"
          />
          <input
            type="checkbox"
            className="absolute top-0 right-0 m-2 group-hover:block bg-black rounded-sm"
            style={{ width: "1.25rem", height: "1.25rem" }}
            defaultChecked
          />
        </div>
      ))}
    </div>
  );
}
